---
- name: Install elixir
  become: yes
  apt:
    state: present
    name:
      - elixir
  tags: [elixir, coding, packages]

- name: Register elixir version
  shell: elixir --version
  register: elixir_version
  tags: [elixir, coding]

- name: Print elixir version
  debug:
    var: elixir_version
    verbosity: 3 # it will only run debug when -vvv or above
  tags: [elixir, coding]
