---
# Base Ansible playbook: Maps configuration of the 'raspberries' group
# to the roles (services) that you want the group's host(s) to run.

- hosts: raspberries
  roles:
    # - essentials
    # - zsh
    - windowing
    # - shairport-sync
    # - vnc-server
    # - hifiberry
    # - waveshare-5inch-touchscreen
    # - alsa
    # - nginx
    # - raspotify
    # - postgres
    # - erlang
    # - elixir
    # - nodejs
    # - ssh-keys
    # - chromium
  vars:
    home: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
