---
- name: update apt cache
  apt:
    update_cache: yes
  become: yes
  tags: [essentials, packages]

- name: upgrade distro
  apt:
    upgrade: dist
  become: yes
  tags: [essentials, packages]

- name: upgrade safe packages
  apt:
    upgrade: safe
  become: yes
  tags: [essentials, packages]

- name: install essential packages
  apt:
    state: present
    name:
      - build-essential
      - curl
      - vim
      - htop
      - git
  become: yes
  tags: [essentials, packages]

- name: remove unused packages and clean up cache
  apt:
    autoclean: yes
    autoremove: yes
  become: yes
  tags: [essentials, packages]
