---
- name: Install X Window system and Openbox window manager
  apt:
    state: present
    pkg:
      - openbox
      - x11-xserver-utils
      - xinit
      - xserver-xorg
      - xserver-xorg-legacy
  become: yes
  tags: [windowing, packages]

- name: Update x window system wrapper config
  ansible.builtin.replace:
    path:  /etc/X11/Xwrapper.config
    regexp: 'allowed_users=console'
    replace: 'allowed_users=anybody'
    backup: yes
  become: yes
  tags: [windowing]

#TODO: https://jonathanmh.com/raspberry-pi-4-kiosk-wall-display-dashboard/
# # For details, see: http://openbox.org/wiki/Help:Autostart
# - name: configure openbox autostart
#   template: src=openbox-autostart.j2 dest=/etc/xdg/openbox/autostart backup=yes
#   become: yes
#   tags: dashboard

- name: Configure xinit to start as a service
  template:
    src: xinit-login.service.j2
    dest: /etc/systemd/system/xinit-login.service
  become: yes
  register: xinit_service
  tags: [windowing, xinit]

- name: Ensure xinit service is running and starts on boot
  systemd:
    name: xinit-login
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  tags: [windowing, xinit]

- name: Restart raspberry if xinit config have been changed
  include_role:
    name: common
    tasks_from: reboot
  when: xinit_service.changed
  tags: hifiberry
