---
- name: install zsh
  apt:
    state: present
    pkg:
      - zsh
  become: yes
  tags: zsh

- name: set zsh as the default shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: yes
  tags: zsh
