---
- name: install zsh
  apt:
    state: present
    name:
      - zsh
  become: yes
  tags: [zsh, packages]

- name: set zsh as the default shell
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: yes
  tags: zsh

- name: add .zshrc config
  copy:
    src: templates/zshrc
    dest: ~/.zshrc
  tags: zsh
