#!/usr/bin/env bash

# NOTE: copy your ssh key before

set -o errexit
set -o pipefail
set -o nounset

cd "$(dirname "$0")/.."

exec ansible-playbook \
  --inventory=ansible/raspberries \
  ansible/hifi.yml \
  "$@"
