---
# Base Ansible playbook: Maps configuration of the 'raspberries' group
# to the roles (services) that you want the group's host(s) to run.

- hosts: raspberries
  roles:
    - hifiberry
    - alsa
    - shairport-sync
    - raspotify
  vars:
    home: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
