---
# Base Ansible playbook: Maps configuration of the 'raspberries' group
# to the roles (services) that you want the group's host(s) to run.

- hosts: raspberries
  roles:
    - nginx
    - postgres
    - erlang
    - elixir
    - nodejs
  vars:
    home: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
