---
- name: Install Postgres and related packages
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2
  tags: [postgres, coding, packages]

- name: Change password for postgres user
  postgresql_user:
    db: postgres
    user: postgres
    password: '{{ postgres.postgres_user_password }}'
  become_user: postgres
  become: yes
  vars:
    ansible_ssh_pipelining: true
  tags: [postgres, coding]

- name: Check if postgres is running
  command: "/etc/init.d/postgresql status"
  register: postgres_status
  tags: [postgres, coding]

- fail:
    msg: "Postgres is not running"
  when: postgres_status.stderr != "" or postgres_status.failed != false
  tags: [postgres, coding]
